#1
SELECT DISTINCT EMP_FNAME, EMP_LNAME
FROM EMPLOYEE NATURAL JOIN HOURS 
WHERE HOUR_RATE > (SELECT AVG(HOUR_RATE) 
					FROM HOURS
					WHERE DATE_WORKED LIKE '2007-05%');
	

#2
SELECT DISTINCT PARK_CODE, PARK_NAME
FROM THEMEPARK NATURAL JOIN TICKET
WHERE TICKET_PRICE > (SELECT AVG(TICKET_PRICE)
					   FROM TICKET);


#3
SELECT DISTINCT(EMP_FNAME), EMP_LNAME, (SELECT AVG(HOUR_RATE) 
							  FROM HOURS) AS AVERAGE,  
							 (SELECT AVG(HOUR_RATE) 
							  FROM HOURS)- HOURS_PER_ATTRACT AS DIFFERENCE, 
							 DATE_WORKED
FROM EMPLOYEE NATURAL JOIN HOURS;


#4
SELECT PARK_NAME 
FROM THEMEPARK 
WHERE PARK_CODE=ANY(SELECT DISTINCT PARK_CODE 
					FROM SALES);


#5
SELECT PARK_NAME 
FROM THEMEPARK 
WHERE PARK_CODE<>ALL(SELECT DISTINCT PARK_CODE 
					 FROM SALES);
